#!/usr/bin/env bash
# script that configures a new Ubuntu machine to Install nginx
sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

sudo systemctl restart nginx
