#!/usr/bin/env bash
# script that configures a new Ubuntu machine to Install nginx
sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ parmanent;' /etc/nginx/sites-available/default

sudo service nginx restart
