#!/usr/bin/env bash
# script that configures a new Ubuntu machine to Install nginx
sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' | sudo dd status=none of=/var/www/html/index.html > /dev/null

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

NEW_RULE="\\\n\tlocation = /redirect_me {\n\t\t return 301 https://www.youtube.com/@innocentsax;\n\t}\n"

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
