#!/usr/bin/env bash
# Script to Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

# Updates the package list and installs Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Adds a custom response header X-Served-By to the default Nginx configuration to identify the server that served the request
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(sudo grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sudo sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Add a redirection rule to the Nginx configuration
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

# Add a custom 404 error page configuration
NEW_RULE="\\\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

# Restart the Nginx service to apply the changes
sudo service nginx restart
