#!/usr/bin/env bash
# script that Install and configure HAproxy on your lb-01 server

sudo apt-get -y update

sudo apt-get -y install haproxy=2.0.\*

echo '
frontend harryjackpro.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 328653-web-01 54.210.96.128
        server 328653-web-02 35.153.79.81
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
