#!/usr/bin/env bash
# Bash script Ubuntu container’s Nginx installation from listening on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
