#!/usr/bin/env bash
# This script hat:Creates the file /var/run/myscript.pid
pidfile="/var/run/myscript.pid"

echo $$ > "$pidfile"
handle_sigterm() {
	echo "I hate the kill command"
	rm -f "$pidfile"
	exit 0
}
handle_sigint() {
	echo "Y U no love me?!"
}
handle_sigquit() {
	rm -f "$pidfile"
	exit 0
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
