#!/usr/bin/env bash
# This script is displaying "Best School" 8 times and badluck and good luck
count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
