#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it’s executed on
ips=$(hostname -I)

IFS=' ' read -ra ADDR <<< "$ips"
for i in "${ADDR[@]}"; do
	if [[ $i =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		echo "$i"
	fi
done
